var para = {
    subject: 'ENGT',
    course: '320',
    course_title: 'Applied Thermal Systems',
    homework_1_due_date: '9/21/2022',
    homework_2_due_date: '9/16/2022',
    homework_3_due_date: '9/19/2022',
    homework_4_due_date: '9/30/2022',
    homework_5_due_date: '9/30/2022',
    homework_6_due_date: '10/3/2022',
    homework_7_due_date: '10/10/2022',
    homework_8_due_date: '10/14/2022',
    homework_9_due_date: '10/17/2022',
    homework_10_due_date: '10/19/2022',
    homework_11_due_date: '10/28/2022',
    homework_12_due_date: '10/31/2022',
    homework_13_due_date: '11/7/2022',
    homework_14_due_date: '11/11/2022',
    homework_15_due_date: '11/14/2022',
    memo_1_due_date: '9/23/2022',
    memo_2_due_date: '9/30/2022',
    memo_3_due_date: '10/7/2022',
    memo_4_due_date: '10/14/2022',
    memo_5_due_date: '10/28/2022',
    memo_6_due_date: '11/4/2022',
    memo_7_due_date: '11/11/2022',
    class_1_date: '9/9/2022',
    class_2_date: '9/12/2022',
    class_3_date: '9/14/2022',
    class_4_date: '9/16/2022',
    class_5_date: '9/19/2022',
    class_6_date: '9/21/2022',
    class_7_date: '9/23/2022',
    class_8_date: '9/26/2022',
    class_9_date: '9/28/2022',
    class_10_date: '9/30/2022',
    class_11_date: '10/3/2022',
    class_12_date: '10/5/2022',
    class_13_date: '10/7/2022',
    class_14_date: '10/10/2022',
    class_15_date: '10/12/2022',
    class_16_date: '10/14/2022',
    class_17_date: '10/17/2022',
    class_18_date: '10/19/2022',
    class_19_date: '10/21/2022',
    class_20_date: '10/24/2022',
    class_21_date: '10/26/2022',
    class_22_date: '10/28/2022',
    class_23_date: '10/31/2022',
    class_24_date: '11/2/2022',
    class_25_date: '11/4/2022',
    class_26_date: '11/7/2022',
    class_27_date: '11/9/2022',
    class_28_date: '11/11/2022',
    class_29_date: '11/14/2022',
    class_30_date: '11/16/2022',
    class_1_week: '1',
    class_2_week: '2',
    class_3_week: '2',
    class_4_week: '2',
    class_5_week: '3',
    class_6_week: '3',
    class_7_week: '3',
    class_8_week: '4',
    class_9_week: '4',
    class_10_week: '4',
    class_11_week: '5',
    class_12_week: '5',
    class_13_week: '5',
    class_14_week: '6',
    class_15_week: '6',
    class_16_week: '6',
    class_17_week: '7',
    class_18_week: '7',
    class_19_week: '7',
    class_20_week: '8',
    class_21_week: '8',
    class_22_week: '8',
    class_23_week: '9',
    class_24_week: '9',
    class_25_week: '9',
    class_26_week: '10',
    class_27_week: '10',
    class_28_week: '10',
    class_29_week: '11',
    class_30_week: '11',
    class_1_topic: '<a href="00.Syllabus.html" target="_blank">00.Syllabus</a><br><a href="01.Introduction.pdf" target="_blank">01.Introduction</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="01.Example%201.html" target="_blank">01.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="01.Example%202.html" target="_blank">01.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="01.Example%203.html" target="_blank">01.Example 3</a>',
    class_2_topic: '<a href="02.Conduction%20Introduction.pdf" target="_blank">02.Conduction Introduction</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="02.Example%201.html" target="_blank">02.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="02.Example%202.html" target="_blank">02.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="02.Example%203.html" target="_blank">02.Example 3</a>',
    class_3_topic: '<a href="03.Heat%20Diffusion%20Equation.pdf" target="_blank">03.Heat Diffusion Equation</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="03.Example%201.html" target="_blank">03.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="03.Example%202.html" target="_blank">03.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="03.Example%203.html" target="_blank">03.Example 3</a>',
    class_4_topic: '<a href="labs/01.Lab Equipment and Thermistor Calibration.html" target="_blank">Lab 1 - Equipment and Thermistor Calibration</a>',
    class_5_topic: 'Content Quiz 1<br><a href="Quiz 1 Formula Sheet.pdf" target="_blank">Quiz 1 Formula Sheet</a>',
    class_6_topic: '<a href="04.Thermoelectric%20Effects.pdf" target="_blank">04.Thermoelectric Effects</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="04.Example%201.html" target="_blank">04.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="04.Example%202.html" target="_blank">04.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="04.Example%203.html" target="_blank">04.Example 3</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="04.Example%204.html" target="_blank">04.Example 4</a>',
    class_7_topic: '<a href="labs/02.Peltier Cooler Investigation.html" target="_blank">Lab 2 - Peltier Cooler Investigation</a>',
    class_8_topic: '<a href="05.Thermal%20Resistance.pdf" target="_blank">05.Thermal Resistance</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="05.Example%201.html" target="_blank">05.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="05.Example%202.html" target="_blank">05.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="05.Example%203.html" target="_blank">05.Example 3</a>',
    class_9_topic: '<a href="06.Extended%20Surfaces.pdf" target="_blank">06.Extended Surfaces</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="06.Example%201.html" target="_blank">06.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="06.Example%202.html" target="_blank">06.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="06.Example%203.html" target="_blank">06.Example 3</a>',
    class_10_topic: '<a href="labs/03.Conduction Investigation.html" target="_blank">Lab 3 - Conduction Investigation</a>',
    class_11_topic: 'Content Quiz 2<br><a href="Quiz 2 Formula Sheet.pdf" target="_blank">Quiz 2 Formula Sheet</a>',
    class_12_topic: '07.Finite Element Analysis',
    class_13_topic: '<a href="labs/04.Fin Investigation.html" target="_blank">Lab 4 - Fin Investigation</a>',
    class_14_topic: '<a href="08.Convection Introduction.pdf" target="_blank">08.Convection Introduction</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="08.Example 1.html" target="_blank">08.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="08.Example 2.html" target="_blank">08.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="08.Example 3.html" target="_blank">08.Example 3</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="08.Example 4.html" target="_blank">08.Example 4</a>',
    class_15_topic: '<a href="09.External Flow.pdf" target="_blank">09.External Flow</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="09.Example 1.html" target="_blank">09.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="09.Example 2.html" target="_blank">09.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="09.Example 3.html" target="_blank">09.Example 3</a>',
    class_16_topic: '<a href="10.Internal Flow.pdf" target="_blank">10.Internal Flow</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="10.Example 1.html" target="_blank">10.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="10.Example 2.html" target="_blank">10.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="10.Example 3.html" target="_blank">10.Example 3</a>',
    class_17_topic: 'No Class',
    class_18_topic: 'Content Quiz 3<br><a href="Quiz 3 Formula Sheet.pdf" target="_blank">Quiz 3 Formula Sheet</a>',
    class_19_topic: 'Lab 5 - Finite Element Analysis Investigation',
    class_20_topic: '<a href="11.Heat Exchangers.pdf" target="_blank">11.Heat Exchangers</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="11.Example 1.html" target="_blank">11.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="11.Example 2.html" target="_blank">11.Example 2</a>',
    class_21_topic: '<a href="12.Effectiveness NTU Method.pdf" target="_blank">12.Effectiveness NTU Method</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="12.Example 1.html" target="_blank">12.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="12.Example 2.html" target="_blank">12.Example 2</a>',
    class_22_topic: '<a href="labs/06.Heat Exchanger Investigation.html" target="_blank">Lab 6 - Heat Exchanger Investigation</a>',
    class_23_topic: 'Content Quiz 4<br><a href="Quiz 4 Formula Sheet.pdf" target="_blank">Quiz 4 Formula Sheet</a>',
    class_24_topic: '<a href="13.Radiation Processes and Properties.pdf" target="_blank">13.Radiation Processes and Properties</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="13.Example 1.html" target="_blank">13.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="13.Example 2.html" target="_blank">13.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="13.Example 3.html" target="_blank">13.Example 3</a>',
    class_25_topic: 'Lab 7 - Radiation Lab',
    class_26_topic: '<a href="14.Surface Radiation.pdf" target="_blank">14.Surface Radiation</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="14.Example 1.html" target="_blank">14.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="14.Example 2.html" target="_blank">14.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="14.Example 3.html" target="_blank">14.Example 3</a>',
    class_27_topic: '<a href="15.Radiation Exchange.pdf" target="_blank">15.Radiation Exchange</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="15.Example 1.html" target="_blank">15.Example 1</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="15.Example 2.html" target="_blank">15.Example 2</a><br>&nbsp;&nbsp;&nbsp;&nbsp;-<a href="15.Example 3.html" target="_blank">15.Example 3</a>',
    class_28_topic: 'No Lab',
    class_29_topic: 'Content Quiz 5<br><a href="Quiz 5 Formula Sheet.pdf" target="_blank">Quiz 5 Formula Sheet</a>',
    class_30_topic: 'No Class',
    class_1_assignment: '<a href="homework/Homework 1 Problem Statement.html" target="_blank">Homework 1</a> (Bonus) due <v k="homework_1_due_date" class="day_abbr short_dot"></v> at 8 AM<br><a href="https://forms.gle/hSET5jfitBHnLGAq9" target="_blank">Submit Here</a>',
    class_2_assignment: '<a href="homework/Homework 2 Problem Statement.html" target="_blank">Homework 2</a> due F 9.16 at 8 AM<br><a href="https://forms.gle/47j5Tqgf4hUw43iA9" target="_blank">Submit Here</a>',
    class_3_assignment: '<a href="homework/Homework 3 Problem Statement.html" target="_blank">Homework 3</a> due M 9.19 at 8 AM<br><a href="https://forms.gle/SvRuPYaV2KySALuz6" target="_blank">Submit Here</a>',
    class_4_assignment: 'Memo 1 due F 9.23 at 8 AM<br><a href="https://forms.gle/ZvpMMVp7mbAvBU1F7" target="_blank">Submit Here</a>',
    class_5_assignment: 'No Assignment',
    class_6_assignment: '<a href="homework/Homework 4 Problem Statement.html" target="_blank">Homework 4</a> due <s>M 9.26</s> F 9.30 at 8 AM<br><a href="https://forms.gle/3CA9GpW41dEJmg2n9" target="_blank">Submit Here</a>',
    class_7_assignment: 'Memo 2 due F 9.30 at 8 AM<br><a href="https://forms.gle/npbmkedj3KpkWsTh9" target="_blank">Submit Here</a>',
    class_8_assignment: '<a href="homework/Homework 5 Problem Statement.html" target="_blank">Homework 5</a> due F 9.30 at 8 AM<br><a href="https://forms.gle/MEc23RnCm4Sz1xC28" target="_blank">Submit Here</a>',
    class_9_assignment: '<a href="homework/Homework 6 Problem Statement.html" target="_blank">Homework 6</a> due M 10.3 at 8 AM<br><a href="https://forms.gle/mAJJUikAjYLFZ3HS7" target="_blank">Submit Here</a>',
    class_10_assignment: 'Memo 3 due F 10.7 at 8 AM<br><a href="https://forms.gle/rDQiydABFoYUWQqJ7" target="_blank">Submit Here</a>',
    class_11_assignment: 'No Assignment',
    class_12_assignment: 'Homework 7 due M 10.10 at 8 AM<br>Submit Here',
    class_13_assignment: 'Memo 4 due F 10.14 at 8 AM<br><a href="https://forms.gle/BVN8JF4LHxfgjzUY9" target="_blank">Submit Here</a>',
    class_14_assignment: '<a href="homework/Homework 8 Problem Statement.html" target="_blank">Homework 8</a> due F 10.14 at 8 AM<br><a href="https://forms.gle/KB3VxoHauvXBt1Mh7" target="_blank">Submit Here</a>',
    class_15_assignment: '<a href="homework/Homework 9 Problem Statement.html" target="_blank">Homework 9</a> due M 10.17 at 8 AM<br><a href="https://forms.gle/mMB64nwKid7reEmp8" target="_blank">Submit Here</a>',
    class_16_assignment: '<a href="homework/Homework 10 Problem Statement.html" target="_blank">Homework 10</a> due W 10.19 at 8 AM<br><a href="https://forms.gle/NKbDsrQKwsiz9acR8" target="_blank">Submit Here</a>',
    class_17_assignment: 'No Assignment',
    class_18_assignment: 'No Assignment',
    class_19_assignment: 'Memo 5 due F 10.28 at 8 AM<br><a href="https://forms.gle/qp9FFYrfkBuTX8ds6" target="_blank">Submit Here</a>',
    class_20_assignment: '<a href="homework/Homework 11 Problem Statement.html" target="_blank">Homework 11</a> due F 10.28 at 8 AM<br><a href="https://forms.gle/ESdkkr4AtWBJdABB7" target="_blank">Submit Here</a>',
    class_21_assignment: '<a href="homework/Homework 12 Problem Statement.html" target="_blank">Homework 12</a> due M 10.31 at 8 AM<br><a href="https://forms.gle/TyQkjbim1BhPidVw7" target="_blank">Submit Here</a>',
    class_22_assignment: 'Memo 6 due F 11.4 at 8 AM<br><a href="https://forms.gle/jBhLKiY79CFwd5YX7" target="_blank">Submit Here</a>',
    class_23_assignment: 'No Assignment',
    class_24_assignment: '<a href="homework/Homework 13 Problem Statement.html" target="_blank">Homework 13</a> due M 11.7 at 8 AM<br><a href="https://forms.gle/VQxpCbFv1b34Hmeb8" target="_blank">Submit Here</a>',
    class_25_assignment: 'Memo 7 due F 11.11 at 8 AM<br><a href="https://forms.gle/qxeoNBGd8FPHEx8h9" target="_blank">Submit Here</a>',
    class_26_assignment: '<a href="homework/Homework 14 Problem Statement.html" target="_blank">Homework 14</a> due F 11.11 at 8 AM<br><a href="https://forms.gle/RPLbmxhKshwuR4Jz8" target="_blank">Submit Here</a>',
    class_27_assignment: '<a href="homework/Homework 15 Problem Statement.html" target="_blank">Homework 15</a> due M 11.14 at 8 AM<br><a href="https://forms.gle/GmQcTarNXkiL4KVVA" target="_blank">Submit Here</a>',
    class_28_assignment: 'No Assignment',
    class_29_assignment: 'No Assignment',
    class_30_assignment: 'No Assignment'
}